from tkinter import*
root=Tk()
def click(event):
    global scvalue
    text=event.widget.cget('text')
    print(text)
    if text=="=":
        if scvalue.get().isdigit():
            value=int(scvalue.get())
        else:
            value=eval(scvalue.get())   
        scvalue.set(value)
        screen.update()     
    elif text=='C':
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()
root.geometry("333x700")
root.title('calculator')
root.wm_iconbitmap("calc_icon.png")
scvalue=StringVar()
screen=Entry(root,textvariable=scvalue,font='lucide 40 bold',bg='grey')
screen.pack(pady=10,fill=X,ipadx=8,padx=10)
f1=Frame(root,bg='grey')
b1=Button(f1,text='9',font='lucide 18 bold',padx=28,pady=18)
b2=Button(f1,text='8',font='lucide 18 bold',padx=28,pady=18)
b3=Button(f1,text='7',font='lucide 18 bold',padx=28,pady=18)
f1.pack()
b1.bind('<Button-1>',click)
b1.pack(side=LEFT,padx=2,pady=2)
b2.bind('<Button-1>',click)
b2.pack(side=LEFT,padx=2,pady=2)
b3.bind('<Button-1>',click)
b3.pack(side=LEFT,padx=2,pady=2)
f2=Frame(root,bg='grey')
b4=Button(f2,text='6',font='lucide 18 bold',padx=28,pady=18)
b5=Button(f2,text='5',font='lucide 18 bold',padx=28,pady=18)
b6=Button(f2,text='4',font='lucide 18 bold',padx=28,pady=18)
f2.pack()
b4.bind('<Button-1>',click)
b4.pack(side=LEFT,padx=2,pady=2)
b5.bind('<Button-1>',click)
b5.pack(side=LEFT,padx=2,pady=2)
b6.bind('<Button-1>',click)
b6.pack(side=LEFT,padx=2,pady=2)
f3=Frame(root,bg='grey')
b7=Button(f3,text='3',font='lucide 18 bold',padx=28,pady=18)
b8=Button(f3,text='2',font='lucide 18 bold',padx=28,pady=18)
b9=Button(f3,text='1',font='lucide 18 bold',padx=28,pady=18)
f3.pack()
b7.bind('<Button-1>',click)
b7.pack(side=LEFT,padx=2,pady=2)
b8.bind('<Button-1>',click)
b8.pack(side=LEFT,padx=2,pady=2)
b9.bind('<Button-1>',click)
b9.pack(side=LEFT,padx=2,pady=2)
f4=Frame(root,bg='grey')
b10=Button(f4,text='0',font='lucide 18 bold',padx=28,pady=18)
b11=Button(f4,text='-',font='lucide 18 bold',padx=28,pady=18)
b12=Button(f4,text='*',font='lucide 18 bold',padx=28,pady=18)
f4.pack()
b10.bind('<Button-1>',click)
b10.pack(side=LEFT,padx=4,pady=4)
b11.bind('<Button-1>',click)
b11.pack(side=LEFT,padx=4,pady=4)
b12.bind('<Button-1>',click)
b12.pack(side=LEFT,padx=4,pady=4)
f5=Frame(root,bg='grey')
b13=Button(f5,text='/',font='lucide 18 bold',padx=28,pady=18)
b14=Button(f5,text='+',font='lucide 18 bold',padx=28,pady=18)
b15=Button(f5,text='=',font='lucide 18 bold',padx=28,pady=18)
f5.pack()
b13.bind('<Button-1>',click)
b13.pack(side=LEFT,padx=4,pady=4)
b14.bind('<Button-1>',click)
b14.pack(side=LEFT,padx=4,pady=4)
b15.bind('<Button-1>',click)
b15.pack(side=LEFT,padx=4,pady=4)
f6=Frame(root,bg='grey')
b16=Button(f6,text='C',font='lucide 18 bold',padx=28,pady=18)
b17=Button(f6,text='%',font='lucide 18 bold',padx=28,pady=18)
b18=Button(f6,text='/',font='lucide 18 bold',padx=28,pady=18)
f6.pack()
b16.bind('<Button-1>',click)
b16.pack(side=LEFT,padx=1,pady=1)
b17.bind('<Button-1>',click)
b17.pack(side=LEFT,padx=1,pady=1)
b18.bind('<Button-1>',click)
b18.pack(side=LEFT,padx=1,pady=1)








root.mainloop() 
